// Mock data for products
export const mockProducts = [
    {
        id: "prod_1",
        name: "Air Jordan 4 Retro Fear",
        brand: "Air Jordan",
        sku: "F9B136-002",
        price: 215,
        description:
            "The Air Jordan 4 Retro Fear features a black, white, and cool grey colorway inspired by the 'Fear Pack' from 2013.",
        category: "sneakers",
        status: "In Stock",
        stock: 25,
        image: "/placeholder.svg?height=200&width=200",
        sales: 42,
    },
    {
        id: "prod_2",
        name: "Yeezy Boost 350 V2 Beluga",
        brand: "Adidas",
        sku: "BB1826",
        price: 320,
        description:
            "The Yeezy Boost 350 V2 Beluga features a grey Primeknit upper with a bright orange stripe.",
        category: "sneakers",
        status: "In Stock",
        stock: 12,
        image: "/placeholder.svg?height=200&width=200",
        sales: 38,
    },
    {
        id: "prod_3",
        name: "Nike Dunk Low Panda",
        brand: "Nike",
        sku: "DD1391-100",
        price: 110,
        description:
            "The Nike Dunk Low Panda features a black and white colorway that's simple yet versatile.",
        category: "sneakers",
        status: "In Stock",
        stock: 50,
        image: "/placeholder.svg?height=200&width=200",
        sales: 65,
    },
    {
        id: "prod_4",
        name: "New Balance 550 White Green",
        brand: "New Balance",
        sku: "BB550WT1",
        price: 120,
        description:
            "The New Balance 550 White Green is a retro basketball sneaker with a clean white upper and green accents.",
        category: "sneakers",
        status: "In Stock",
        stock: 30,
        image: "/placeholder.svg?height=200&width=200",
        sales: 29,
    },
    {
        id: "prod_5",
        name: "Air Jordan 1 High OG Chicago",
        brand: "Air Jordan",
        sku: "DZ5485-612",
        price: 180,
        description:
            "The Air Jordan 1 High OG Chicago is a reissue of the iconic red, white, and black colorway.",
        category: "sneakers",
        status: "Out of Stock",
        stock: 0,
        image: "/placeholder.svg?height=200&width=200",
        sales: 52,
    },
];

// Mock data for orders
export const mockOrders = [
    {
        id: "ord_1",
        orderNumber: "ORD-12345",
        date: "2023-04-15T10:30:00Z",
        customer: {
            name: "John Smith",
            email: "john.smith@example.com",
            phone: "+44 7123 456789",
        },
        items: [
            {
                name: "Air Jordan 4 Retro Fear",
                sku: "F9B136-002",
                price: 215,
                size: "UK 9",
                quantity: 1,
                image: "/placeholder.svg?height=80&width=80",
            },
        ],
        subtotal: 215,
        shipping: 10,
        discount: 0,
        total: 225,
        status: "delivered",
        shippingAddress: {
            line1: "123 Main Street",
            line2: "Apt 4B",
            city: "London",
            postalCode: "E1 6AN",
            country: "United Kingdom",
        },
        paymentMethod: "Credit Card (Visa ending in 4242)",
    },
    {
        id: "ord_2",
        orderNumber: "ORD-12346",
        date: "2023-04-16T14:20:00Z",
        customer: {
            name: "Emma Johnson",
            email: "emma.johnson@example.com",
            phone: "+44 7234 567890",
        },
        items: [
            {
                name: "Nike Dunk Low Panda",
                sku: "DD1391-100",
                price: 110,
                size: "UK 6",
                quantity: 1,
                image: "/placeholder.svg?height=80&width=80",
            },
            {
                name: "Adidas Samba OG",
                sku: "B75806",
                price: 90,
                size: "UK 7",
                quantity: 1,
                image: "/placeholder.svg?height=80&width=80",
            },
        ],
        subtotal: 200,
        shipping: 10,
        discount: 20,
        total: 190,
        status: "shipped",
        shippingAddress: {
            line1: "456 High Street",
            line2: "",
            city: "Manchester",
            postalCode: "M1 1AD",
            country: "United Kingdom",
        },
        paymentMethod: "PayPal",
    },
    {
        id: "ord_3",
        orderNumber: "ORD-12347",
        date: "2023-04-17T09:15:00Z",
        customer: {
            name: "David Williams",
            email: "david.williams@example.com",
            phone: "+44 7345 678901",
        },
        items: [
            {
                name: "Yeezy Boost 350 V2 Beluga",
                sku: "BB1826",
                price: 320,
                size: "UK 10",
                quantity: 1,
                image: "/placeholder.svg?height=80&width=80",
            },
        ],
        subtotal: 320,
        shipping: 10,
        discount: 0,
        total: 330,
        status: "processing",
        shippingAddress: {
            line1: "789 Park Lane",
            line2: "Floor 3",
            city: "Birmingham",
            postalCode: "B1 1AA",
            country: "United Kingdom",
        },
        paymentMethod: "Credit Card (Mastercard ending in 5678)",
    },
    {
        id: "ord_4",
        orderNumber: "ORD-12348",
        date: "2023-04-18T16:45:00Z",
        customer: {
            name: "Sophia Brown",
            email: "sophia.brown@example.com",
            phone: "+44 7456 789012",
        },
        items: [
            {
                name: "New Balance 550 White Green",
                sku: "BB550WT1",
                price: 120,
                size: "UK 5.5",
                quantity: 1,
                image: "/placeholder.svg?height=80&width=80",
            },
        ],
        subtotal: 120,
        shipping: 10,
        discount: 0,
        total: 130,
        status: "pending",
        shippingAddress: {
            line1: "101 Queen Street",
            line2: "",
            city: "Glasgow",
            postalCode: "G1 3DH",
            country: "United Kingdom",
        },
        paymentMethod: "Apple Pay",
    },
    {
        id: "ord_5",
        orderNumber: "ORD-12349",
        date: "2023-04-19T11:30:00Z",
        customer: {
            name: "Oliver Taylor",
            email: "oliver.taylor@example.com",
            phone: "+44 7567 890123",
        },
        items: [
            {
                name: "Air Jordan 1 High OG Chicago",
                sku: "DZ5485-612",
                price: 180,
                size: "UK 8",
                quantity: 1,
                image: "/placeholder.svg?height=80&width=80",
            },
        ],
        subtotal: 180,
        shipping: 10,
        discount: 0,
        total: 190,
        status: "cancelled",
        shippingAddress: {
            line1: "202 King's Road",
            line2: "Apt 7C",
            city: "Edinburgh",
            postalCode: "EH1 1AA",
            country: "United Kingdom",
        },
        paymentMethod: "Credit Card (Amex ending in 1234)",
    },
];
