import type { UserType, OrderType, AddressType, ProductType } from "./schemas";

// Mock data for products
export const mockProducts: ProductType[] = [
    {
        id: "prod_1",
        name: "Air Jordan 4 Retro Fear",
        description:
            "The Air Jordan 4 Retro Fear features a black, white, and cool grey colorway inspired by the 'Fear Pack' from 2013.",
        variants: [
            { size: "UK 7", price: 215, stock: 5 },
            { size: "UK 8", price: 215, stock: 3 },
            { size: "UK 9", price: 215, stock: 8 },
            { size: "UK 9.5", price: 220, stock: 2 },
            { size: "UK 10", price: 215, stock: 4 },
            { size: "UK 11", price: 225, stock: 3 },
        ],
        category: {
            id: "cat_1",
            name: "Sneakers",
            description: "Premium athletic and casual footwear",
            promotion: {
                type: ["New Release", "Limited Edition"],
                details: "Just released! Limited quantities available.",
            },
        },
        isFeatured: true,
        tags: ["Air Jordan", "Basketball", "Retro", "Limited Edition"],
        image: "/placeholder.svg?height=200&width=200",
        createdAt: "2023-04-15T10:30:00Z",
        updatedAt: "2023-04-15T10:30:00Z",
    },
    {
        id: "prod_2",
        name: "Yeezy Boost 350 V2 Beluga",
        description:
            "The Yeezy Boost 350 V2 Beluga features a grey Primeknit upper with a bright orange stripe.",
        variants: [
            { size: "UK 6", price: 320, stock: 2 },
            { size: "UK 7", price: 320, stock: 3 },
            { size: "UK 8", price: 320, stock: 1 },
            { size: "UK 9", price: 330, stock: 4 },
            { size: "UK 10", price: 330, stock: 2 },
            { size: "UK 11", price: 340, stock: 0 },
            { size: "UK 12", price: 350, stock: 0 },
        ],
        category: {
            id: "cat_1",
            name: "Sneakers",
            description: "Designer collaboration footwear",
            promotion: {
                type: ["Popular", "Resale Value"],
                details: "High resale value, collector's item.",
            },
        },
        isFeatured: true,
        tags: ["Yeezy", "Adidas", "Kanye West", "Boost"],
        image: "/placeholder.svg?height=200&width=200",
        createdAt: "2023-04-16T14:20:00Z",
        updatedAt: "2023-04-16T14:20:00Z",
    },
    {
        id: "prod_3",
        name: "Nike Dunk Low Panda",
        description:
            "The Nike Dunk Low Panda features a black and white colorway that's simple yet versatile.",
        variants: [
            { size: "UK 3", price: 110, stock: 5 },
            { size: "UK 4", price: 110, stock: 7 },
            { size: "UK 5", price: 110, stock: 6 },
            { size: "UK 6", price: 110, stock: 8 },
            { size: "UK 7", price: 110, stock: 10 },
            { size: "UK 8", price: 110, stock: 9 },
            { size: "UK 9", price: 110, stock: 5 },
            { size: "UK 10", price: 120, stock: 0 },
            { size: "UK 11", price: 120, stock: 0 },
        ],
        category: {
            id: "cat_1",
            name: "Sneakers",
            description: "Casual lifestyle footwear",
            promotion: {
                type: ["Bestseller", "Trending"],
                details: "Our most popular colorway, restocked weekly.",
            },
        },
        isFeatured: true,
        tags: ["Nike", "Dunk", "Casual", "Everyday"],
        image: "/placeholder.svg?height=200&width=200",
        createdAt: "2023-04-17T09:15:00Z",
        updatedAt: "2023-04-17T09:15:00Z",
    },
    {
        id: "prod_4",
        name: "New Balance 550 White Green",
        description:
            "The New Balance 550 White Green is a retro basketball sneaker with a clean white upper and green accents.",
        variants: [
            { size: "UK 6", price: 120, stock: 4 },
            { size: "UK 7", price: 120, stock: 6 },
            { size: "UK 8", price: 120, stock: 8 },
            { size: "UK 9", price: 120, stock: 7 },
            { size: "UK 10", price: 120, stock: 5 },
            { size: "UK 11", price: 130, stock: 0 },
        ],
        category: {
            id: "cat_1",
            name: "Sneakers",
            description: "Retro-inspired athletic footwear",
            promotion: {
                type: ["Trending", "Summer Collection"],
                details: "Perfect for summer, versatile colorway.",
            },
        },
        isFeatured: false,
        tags: ["New Balance", "Retro", "Basketball", "Casual"],
        image: "/placeholder.svg?height=200&width=200",
        createdAt: "2023-04-18T16:45:00Z",
        updatedAt: "2023-04-18T16:45:00Z",
    },
    {
        id: "prod_5",
        name: "Air Jordan 1 High OG Chicago",
        description:
            "The Air Jordan 1 High OG Chicago is a reissue of the iconic red, white, and black colorway.",
        variants: [
            { size: "UK 7", price: 180, stock: 0 },
            { size: "UK 8", price: 180, stock: 0 },
            { size: "UK 9", price: 190, stock: 0 },
            { size: "UK 10", price: 190, stock: 0 },
            { size: "UK 11", price: 200, stock: 0 },
            { size: "UK 12", price: 200, stock: 0 },
        ],
        category: {
            id: "cat_1",
            name: "Sneakers",
            description: "Iconic basketball heritage footwear",
            promotion: {
                type: ["Classic", "Heritage", "Collector's Item"],
                details: "The iconic colorway that started it all.",
            },
        },
        isFeatured: true,
        tags: ["Air Jordan", "Basketball", "Iconic", "Chicago"],
        image: "/placeholder.svg?height=200&width=200",
        createdAt: "2023-04-19T11:30:00Z",
        updatedAt: "2023-04-19T11:30:00Z",
    },
];

// Mock data for users
export const mockUsers: UserType[] = [
    {
        id: "user_1",
        name: "John Smith",
        email: "john.smith@example.com",
        passwordHash: "hashed_password_1",
        phone: "+44 7123 456789",
        provider: "credentials",
        isVerified: true,
        role: "user",
        addresses: [
            {
                street: "123 Main Street",
                city: "London",
                postalCode: "E1 6AN",
                country: "United Kingdom",
                district: "East London",
                isDefault: true,
            },
        ],
        cart: [
            {
                productId: "prod_1",
                size: "UK 9",
                quantity: 1,
                price: 1,
                image: "/placeholder.svg?height=200&width=200",
                name: "Air Jordan 4 Retro Fear",
            },
        ],
        createdAt: "2023-01-15T10:30:00Z",
        updatedAt: "2023-03-22T14:45:00Z",
    },
    {
        id: "user_2",
        name: "Emma Johnson",
        email: "emma.johnson@example.com",
        phone: "+44 7234 567890",
        provider: "google",
        providerId: "google-oauth2|123456789",
        isVerified: true,
        role: "admin",
        addresses: [
            {
                street: "456 High Street",
                city: "Manchester",
                postalCode: "M1 1AD",
                country: "United Kingdom",
                isDefault: true,
            },
        ],
        cart: [],
        createdAt: "2023-02-10T09:15:00Z",
        updatedAt: "2023-04-05T11:20:00Z",
    },
    {
        id: "user_3",
        name: "David Williams",
        email: "david.williams@example.com",
        passwordHash: "hashed_password_3",
        phone: "+44 7345 678901",
        provider: "credentials",
        isVerified: true,
        role: "user",
        addresses: [
            {
                street: "789 Park Lane",
                city: "Birmingham",
                postalCode: "B1 1AA",
                country: "United Kingdom",
                district: "City Centre",
                isDefault: true,
            },
            {
                street: "101 Business Avenue",
                city: "Birmingham",
                postalCode: "B2 2BB",
                country: "United Kingdom",
                district: "Business District",
                isDefault: false,
            },
        ],
        cart: [
            {
                productId: "prod_2",
                size: "UK 10",
                quantity: 1,
                price: 1,
                image: "/placeholder.svg?height=200&width=200",
                name: "Air Jordan 4 Retro Fear",
            },
        ],
        createdAt: "2023-02-22T15:40:00Z",
        updatedAt: "2023-03-30T09:25:00Z",
    },
    {
        id: "user_4",
        name: "Sophia Brown",
        email: "sophia.brown@example.com",
        passwordHash: "hashed_password_4",
        phone: "+44 7456 789012",
        provider: "credentials",
        isVerified: false,
        role: "user",
        addresses: [],
        cart: [],
        createdAt: "2023-03-05T12:10:00Z",
        updatedAt: "2023-03-05T12:10:00Z",
    },
    {
        id: "user_5",
        name: "Oliver Taylor",
        email: "oliver.taylor@example.com",
        phone: "+44 7567 890123",
        provider: "google",
        providerId: "google-oauth2|987654321",
        isVerified: true,
        role: "user",
        addresses: [
            {
                street: "202 King's Road",
                city: "Edinburgh",
                postalCode: "EH1 1AA",
                country: "United Kingdom",
                district: "Old Town",
                isDefault: true,
            },
        ],
        cart: [],
        createdAt: "2023-03-18T16:50:00Z",
        updatedAt: "2023-04-10T13:15:00Z",
    },
];

export const mockCarouselProducts = [
    {
        name: "Midnight Oud Attar",
        price: 49.99,
        tags: ["Oud", "Oriental", "Unisex"],
        image: "https://placehold.co/600x600/png",
        size: "10ml",
        concentration: "Pure Attar Oil",
        productLink: "/products/midnight-oud",
    },
    {
        name: "Rose Taifi Essence",
        price: 39.99,
        tags: ["Floral", "Rose", "Feminine"],
        image: "https://placehold.co/600x600/png",
        size: "25ml",
        concentration: "Eau de Parfum",
        productLink: "/products/rose-taifi",
    },
    {
        name: "Amber Musk",
        price: 59.99,
        tags: ["Amber", "Musk", "Long-lasting"],
        image: "https://placehold.co/600x600/png",
        size: "50ml",
        concentration: "Concentrated Perfume Oil",
        productLink: "/products/amber-musk",
    },
    {
        name: "Sandalwood Elixir",
        price: 69.99,
        tags: ["Woody", "Sandalwood", "Unisex"],
        image: "https://placehold.co/600x600/png",
        size: "30ml",
        concentration: "Pure Attar",
        productLink: "/products/sandalwood-elixir",
    },
    {
        name: "Jasmine Dreams",
        price: 45.99,
        tags: ["Floral", "Jasmine", "Feminine"],
        image: "https://placehold.co/600x600/png",
        size: "15ml",
        concentration: "Attar Oil",
        productLink: "/products/jasmine-dreams",
    },
    {
        name: "Vetiver Noir",
        price: 79.99,
        tags: ["Woody", "Earthy", "Masculine"],
        image: "https://placehold.co/600x600/png",
        size: "50ml",
        concentration: "Eau de Parfum",
        productLink: "/products/vetiver-noir",
    },
    {
        name: "Saffron Royale",
        price: 89.99,
        tags: ["Spicy", "Saffron", "Luxury"],
        image: "https://placehold.co/600x600/png",
        size: "30ml",
        concentration: "Parfum",
        productLink: "/products/saffron-royale",
    },
    {
        name: "Citrus Breeze",
        price: 34.99,
        tags: ["Fresh", "Citrus", "Summer"],
        image: "https://placehold.co/600x600/png",
        size: "50ml",
        concentration: "Eau de Cologne",
        productLink: "/products/citrus-breeze",
    },
];

// Helper function to get a default address for a user
const getDefaultAddress = (userId: string): AddressType => {
    const user = mockUsers.find((u) => u.id === userId);
    if (!user || !user.addresses || user.addresses.length === 0) {
        return {
            street: "Unknown Address",
            city: "Unknown City",
            postalCode: "Unknown",
            country: "Unknown Country",
        };
    }

    const defaultAddress =
        user.addresses.find((a) => a.isDefault) || user.addresses[0];
    return defaultAddress;
};

// Mock data for orders
export const mockOrders: OrderType[] = [
    {
        id: "ord_1",
        userId: "user_1",
        customer: {
            name: "John Smith",
            email: "john.smith@example.com",
            phone: "+44 7123 456789",
        },
        items: [
            {
                productId: "prod_1",
                name: "Air Jordan 4 Retro Fear",
                price: 215,
                size: "UK 9",
                quantity: 1,
                image: "/placeholder.svg?height=80&width=80",
            },
        ],
        totalAmount: 225,
        status: "delivered",
        paymentStatus: "paid",
        paymentMethod: "sslcommerz",
        shippingAddress: getDefaultAddress("user_1"),
        createdAt: "2023-04-15T10:30:00Z",
        updatedAt: "2023-04-17T14:30:00Z",
    },
    {
        id: "ord_2",
        userId: "user_3",
        customer: {
            name: "David Williams",
            email: "david.williams@example.com",
            phone: "+44 7345 678901",
        },
        items: [
            {
                productId: "prod_3",
                name: "Nike Dunk Low Panda",
                price: 110,
                size: "UK 6",
                quantity: 1,
                image: "/placeholder.svg?height=80&width=80",
            },
            {
                productId: "prod_4",
                name: "New Balance 550 White Green",
                price: 90,
                size: "UK 7",
                quantity: 1,
                image: "/placeholder.svg?height=80&width=80",
            },
        ],
        totalAmount: 210,
        status: "shipped",
        paymentStatus: "paid",
        paymentMethod: "sslcommerz",
        shippingAddress: getDefaultAddress("user_3"),
        createdAt: "2023-04-16T14:20:00Z",
        updatedAt: "2023-04-18T09:15:00Z",
    },
    {
        id: "ord_3",
        userId: "user_5",
        customer: {
            name: "Oliver Taylor",
            email: "oliver.taylor@example.com",
            phone: "+44 7567 890123",
        },
        items: [
            {
                productId: "prod_2",
                name: "Yeezy Boost 350 V2 Beluga",
                price: 320,
                size: "UK 10",
                quantity: 1,
                image: "/placeholder.svg?height=80&width=80",
            },
        ],
        totalAmount: 330,
        status: "processing",
        paymentStatus: "paid",
        paymentMethod: "sslcommerz",
        shippingAddress: getDefaultAddress("user_5"),
        createdAt: "2023-04-17T09:15:00Z",
        updatedAt: "2023-04-17T15:30:00Z",
    },
    {
        id: "ord_4",
        userId: "user_4",
        customer: {
            name: "Sophia Brown",
            email: "sophia.brown@example.com",
            phone: "+44 7456 789012",
        },
        items: [
            {
                productId: "prod_4",
                name: "New Balance 550 White Green",
                price: 120,
                size: "UK 5.5",
                quantity: 1,
                image: "/placeholder.svg?height=80&width=80",
            },
        ],
        totalAmount: 130,
        status: "pending",
        paymentStatus: "unpaid",
        paymentMethod: "sslcommerz",
        shippingAddress: {
            street: "101 Queen Street",
            city: "Glasgow",
            postalCode: "G1 3DH",
            country: "United Kingdom",
        },
        createdAt: "2023-04-18T16:45:00Z",
        updatedAt: "2023-04-18T16:45:00Z",
    },
    {
        id: "ord_5",
        userId: "user_2",
        customer: {
            name: "Emma Johnson",
            email: "emma.johnson@example.com",
            phone: "+44 7234 567890",
        },
        items: [
            {
                productId: "prod_5",
                name: "Air Jordan 1 High OG Chicago",
                price: 180,
                size: "UK 8",
                quantity: 1,
                image: "/placeholder.svg?height=80&width=80",
            },
        ],
        totalAmount: 190,
        status: "cancelled",
        paymentStatus: "refunded",
        paymentMethod: "sslcommerz",
        shippingAddress: getDefaultAddress("user_2"),
        notes: "Customer requested cancellation due to delayed shipping",
        createdAt: "2023-04-19T11:30:00Z",
        updatedAt: "2023-04-21T09:45:00Z",
    },
];
