import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { Search, ShoppingBag } from "lucide-react";
import { MainNav } from "@/components/main-nav";
import Header from "@/components/header";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Project AT",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <Header />

                {children}

                <footer className="border-t border-accent bg-black text-white">
                    <div className="container px-4 py-8">
                        <div className="flex flex-col md:flex-row justify-between items-center">
                            <p className="text-sm mb-4 md:mb-0 lg:ml-24">
                                © 2025 OLFACTIVE. All rights reserved.
                            </p>
                            <div className="flex space-x-4">
                                <Link
                                    href="#"
                                    className="text-sm uppercase tracking-widest hover:underline"
                                >
                                    Instagram
                                </Link>
                                <Link
                                    href="#"
                                    className="text-sm uppercase tracking-widest hover:underline"
                                >
                                    Twitter
                                </Link>
                                <Link
                                    href="#"
                                    className="text-sm uppercase tracking-widest hover:underline"
                                >
                                    Pinterest
                                </Link>
                            </div>
                        </div>
                    </div>
                </footer>
            </body>
        </html>
    );
}
